language: bash
services: docker

env:
  - VERSION=8
  - VERSION=10

before_script:
  - env
  - cd "$VERSION"
  - image="shion/node:${VERSION}"

script:
  - docker build ./ -t "$image"

after_script:
  - docker images